root_dir: SimCLR_manifold_learning/saved-models/simclr/caltech-101
log_dir: ./logs
freeze_layer: True
# Setup
setup: simclr
KNN_acc: simclr-caltech101.txt
# Model
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: caltech-101
val_db_name: caltech-101
num_classes: 101

# Loss
criterion: simclr
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 500
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 1
num_workers: 8

# Transformations
augmentation_strategy: simclr
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]
